{{- if .Values.runtimes.enabled }}
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: deepspeed-distributed
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    trainer.kubeflow.org/framework: deepspeed
spec:
  mlPolicy:
    numNodes: 1
    mpi:
      numProcPerNode: 1
      mpiImplementation: OpenMPI
      sshAuthMountPath: /home/mpiuser/.ssh
      runLauncherAsNode: true
  template:
    spec:
      network:
        publishNotReadyAddresses: true
      successPolicy:
        operator: All
        targetReplicatedJobs:
          - launcher
      replicatedJobs:
        - name: launcher
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: "{{ include "trainer.suseImageRegistry" (dict "ctx" . "registry" .Values.runtimes.deepspeed.image.registry) }}/{{ .Values.runtimes.deepspeed.image.repository }}{{- if .Values.runtimes.deepspeed.image.digest }}@{{ .Values.runtimes.deepspeed.image.digest }}{{- else }}:{{ .Values.runtimes.deepspeed.image.tag }}{{- end }}"
                      securityContext:
                        runAsUser: 1000
        - name: node
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: "{{ include "trainer.suseImageRegistry" (dict "ctx" . "registry" .Values.runtimes.deepspeed.image.registry) }}/{{ .Values.runtimes.deepspeed.image.repository }}{{- if .Values.runtimes.deepspeed.image.digest }}@{{ .Values.runtimes.deepspeed.image.digest }}{{- else }}:{{ .Values.runtimes.deepspeed.image.tag }}{{- end }}"
                      securityContext:
                        runAsUser: 1000
                      command:
                        - /usr/sbin/sshd
                      args:
                        - -De
                        - -f
                        - /home/mpiuser/.sshd_config
                      readinessProbe:
                        tcpSocket:
                          port: 2222
                        initialDelaySeconds: 5
{{- end }}
