{{- if .Values.runtimes.enabled }}
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: torch-distributed
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 1
    torch:
      numProcPerNode: auto
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: "{{ with (coalesce .Values.global.imageRegistry .Values.runtimes.torch.distributed.image.registry) }}{{ . }}/{{ end }}{{ .Values.runtimes.torch.distributed.image.repository }}{{- if .Values.runtimes.torch.distributed.image.digest }}@{{ .Values.runtimes.torch.distributed.image.digest }}{{- else }}:{{ .Values.runtimes.torch.distributed.image.tag }}{{- end }}"
{{- end }}
