{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.imagePullSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: kubeflow-propagate-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  namespaceSelector:
    {{- toYaml $.Values.externalSecrets.namespaceSelector | nindent 4 }}
  refreshTime: {{ $.Values.externalSecrets.refreshInterval }}
  externalSecretSpec:
    refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
    secretStoreRef:
      name: kubeflow-registry-secrets
      kind: ClusterSecretStore
    target:
      name: {{ .name }}
      creationPolicy: Owner
      deletionPolicy: Delete
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: {{ .name }}
          property: .dockerconfigjson
{{- end }}
{{- end }}
