{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubeflow-registry-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.externalSecrets.imagePullSecrets.sourceNamespace }}
      auth:
        serviceAccount:
          name: eso-kubeflow-reader
          namespace: {{ .Values.externalSecrets.imagePullSecrets.sourceNamespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ .Values.externalSecrets.imagePullSecrets.sourceNamespace }}
{{- end }}
