apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - {{ .Values.mariadb.persistence.accessMode }}
  {{- if .Values.mariadb.persistence.storageClass }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.storageSize }}
