{{- if .Values.global.oauth2Proxy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kubeflow-oauth2-proxy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
{{- end }}
