apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  name: jupyter-web-app-notebook-template
  namespace: kubeflow
data:
  notebook_template.yaml: |-
    {{- tpl ($.Files.Get "files/notebook_template.yaml") . | nindent 4 -}}
