{{- range .Values.additionalUsers }}
{{- $emailSlug := .email | lower | replace "." "-" | replace "@" "--" }}
{{- $namespaceName := .namespace | default $emailSlug }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor
  namespace: {{ $namespaceName }}
{{- end }}
