apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: default
spec:
  container:
    name: storage-initializer
    image: "{{ with (coalesce .Values.global.imageRegistry .Values.storageInitializer.image.registry) }}{{ . }}/{{ end }}{{ .Values.storageInitializer.image.repository }}{{- if .Values.storageInitializer.image.digest }}@{{ .Values.storageInitializer.image.digest }}{{- else }}:{{ .Values.storageInitializer.image.tag }}{{- end }}"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: gs://
    - prefix: s3://
    - prefix: hdfs://
    - prefix: hf://
    - prefix: webhdfs://
    - regex: "https://(.+?).blob.core.windows.net/(.+)"
    - regex: "https://(.+?).file.core.windows.net/(.+)"
    - regex: "https?://(.+)/(.+)"
  workloadType: initContainer
