global:
  # -- Global override for container image registry
  imageRegistry: ""
  # -- Global override for container image pull secrets
  imagePullSecrets: []
image:
  registry: stgregistry.suse.com
  repository: ai/containers/kubeflow/kubeflow/poddefaults-webhook
  tag: v1.10.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

containerPort: 4443

service:
  port: 443
  targetPort: 4443
