apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry-ui
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-registry-ui
  namespace: kubeflow
