apiVersion: v1
data:
  VWA_APP_SECURE_COOKIES: {{ .Values.parametersConfigMap.VWA_APP_SECURE_COOKIES | quote }}
  VWA_CLUSTER_DOMAIN: {{ .Values.parametersConfigMap.VWA_CLUSTER_DOMAIN | quote }}
  VWA_PREFIX: {{ .Values.parametersConfigMap.VWA_PREFIX | quote }}
  VWA_USERID_HEADER: {{ .Values.parametersConfigMap.VWA_USERID_HEADER | quote }}
  VWA_USERID_PREFIX: {{ .Values.parametersConfigMap.VWA_USERID_PREFIX | quote }}
kind: ConfigMap
metadata:
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
  name: volumes-web-app-parameters-57h65c44mg
  namespace: kubeflow
