apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: model-registry-service
  namespace: kubeflow
spec:
  action: ALLOW
  selector:
    matchLabels:
      component: model-registry-server
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
  - when:
    - key: request.headers[authorization]
      values:
      - "*"
    - key: request.headers[kubeflow-userid]
      notValues:
      - "*"
