apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry-ui
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-registry-ui
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        - kubeflow
  selector:
    matchLabels:
      app: model-registry
      app.kubernetes.io/component: model-registry-ui
      app.kubernetes.io/name: model-registry
      kustomize.component: model-registry
