apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admission-webhook.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete
