{{- if .Values.jobset.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: jobset-controller-manager
  name: jobset-controller-manager
  namespace: kubeflow
{{- end }}
