apiVersion: v1
kind: Service
metadata:
  name: model-registry-service
  namespace: kubeflow
  labels:
    component: model-registry-server
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http-api
    port: {{ .Values.service.port }}
    protocol: TCP
    appProtocol: http
    targetPort: http-api
  selector:
    component: model-registry-server
