global:
  # -- Global override for container image registry
  imageRegistry: ""
  # -- Global override for container image pull secrets
  imagePullSecrets: []

controller:
  image:
    registry: registry.suse.com
    repository: ai/containers/katib-controller
    tag: v0.19.0
    pullPolicy: IfNotPresent
    digest: ""  # optional: sha256:...

ui:
  image:
    registry: registry.suse.com
    repository: ai/containers/katib-ui
    tag: v0.19.0
    pullPolicy: IfNotPresent
    digest: ""  # optional: sha256:...

dbManager:
  image:
    registry: registry.suse.com
    repository: ai/containers/katib-db-manager
    tag: v0.19.0
    pullPolicy: IfNotPresent
    digest: ""  # optional: sha256:...
