global:
  # -- Global override for container image registry
  imageRegistry: ""
  # -- Global override for SUSE AI container image registry (e.g. staging registry)
  suseRegistry: ""
  # -- Global override for container image pull secrets
  imagePullSecrets: []
  # -- Global override for image pull policy
  imagePullPolicy: IfNotPresent

# Fallback image registry when global.imageRegistry and global.suseRegistry are not set
image:
  registry: registry.suse.com

controller:
  image:
    registry: registry.suse.com
    repository: ai/containers/knative-releases/knative.dev/eventing/cmd/controller
    tag: "v1.22.0"  # unused when digest is set
    digest: ""  # e.g. sha256:abcd1234... (overrides tag when set)
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    APISERVER_RA_IMAGE:
      registry: registry.suse.com
      repository: ai/containers/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter
      tag: "v1.22.0"  # unused when digest is set
      digest: ""  # e.g. sha256:abcd1234... (overrides tag when set)
      pullPolicy: IfNotPresent

webhook:
  image:
    registry: registry.suse.com
    repository: ai/containers/knative-releases/knative.dev/eventing/cmd/webhook
    tag: "v1.22.0"  # unused when digest is set
    digest: ""  # e.g. sha256:abcd1234... (overrides tag when set)
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 50Mi

pingsource:
  image:
    registry: registry.suse.com
    repository: ai/containers/knative-releases/knative.dev/eventing/cmd/mtping
    tag: "v1.22.0"  # unused when digest is set
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 125m
      memory: 64Mi
