apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-trainer-edit
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-trainer-admin: "true"
rules:
  - apiGroups:
      - trainer.kubeflow.org
    resources:
      - trainingruntimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - trainer.kubeflow.org
    resources:
      - trainjobs
    verbs:
      - create
      - patch
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
