{{- $root := . -}}
{{- range .Values.additionalUsers }}
{{- $emailSlug := .email | lower | replace "." "-" | replace "@" "--" }}
{{- $namespaceName := .namespace | default $emailSlug }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-visualizationserver
  name: ml-pipeline-visualizationserver
  namespace: {{ $namespaceName }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
  template:
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
    spec:
      containers:
      - image: "{{ include "user-namespace.suseImageRegistry" (dict "ctx" $root "registry" $root.Values.pipelines.visualizationServer.registry) }}/{{ $root.Values.pipelines.visualizationServer.repository }}{{- if $root.Values.pipelines.visualizationServer.digest }}@{{ $root.Values.pipelines.visualizationServer.digest }}{{- else }}:{{ $root.Values.pipelines.visualizationServer.tag }}{{- end }}"
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-visualizationserver
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 1Gi
      serviceAccountName: default-editor
{{- end }}
