apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: kubeflow-trainer-controller-manager
  name: kubeflow-trainer-controller-manager
  namespace: kubeflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: kubeflow-trainer-controller-manager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        control-plane: kubeflow-trainer-controller-manager
    spec:
      {{- include "trainer.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: "{{ include "trainer.suseImageRegistry" (dict "ctx" . "registry" .Values.image.registry) }}/{{ .Values.image.repository }}{{- if .Values.image.digest }}@{{ .Values.image.digest }}{{- else }}:{{ .Values.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --config=/controller_manager_config.yaml
        - --zap-log-level=2
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-certs
          readOnly: true
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
          readOnly: true
      serviceAccountName: kubeflow-trainer-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tmp-dir
        emptyDir: {}
      - name: webhook-certs
        secret:
          defaultMode: 420
          secretName: kubeflow-trainer-webhook-cert
      - name: manager-config
        configMap:
          name: kubeflow-trainer-config
