apiVersion: v2
appVersion: 2.16.0
description: A Helm chart for Kubernetes
name: kubeflow-pipelines
type: application
version: 0.2.4

dependencies:
  - name: mariadb
    version: "0.2.0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: mariadb.enabled
