apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-scheduledworkflow
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-scheduledworkflow
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-scheduledworkflow
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
      labels:
        app: ml-pipeline-scheduledworkflow
        app.kubernetes.io/component: ml-pipeline
        app.kubernetes.io/name: kubeflow-pipelines
        application-crd-id: kubeflow-pipelines
    spec:
      {{- include "kubeflow-pipelines.imagePullSecrets" . | nindent 6 }}
      containers:
      - env:
        - name: NAMESPACE
          value: ''
        - name: CRON_SCHEDULE_TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: cronScheduleTimezone
              name: pipeline-install-config
        image: "{{- $registry := include "kubeflow-pipelines.suseImageRegistry" (dict "ctx" . "registry" .Values.scheduledWorkflow.image.registry) -}}{{- if $registry }}{{ $registry }}/{{ end }}{{ .Values.scheduledWorkflow.image.repository }}{{- if .Values.scheduledWorkflow.image.digest }}@{{ .Values.scheduledWorkflow.image.digest }}{{- else }}:{{ .Values.scheduledWorkflow.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.scheduledWorkflow.image.pullPolicy }}
        name: ml-pipeline-scheduledworkflow
        {{- with .Values.scheduledWorkflow.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: ml-pipeline-scheduledworkflow
