apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: workflow-controller
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      labels:
        app: workflow-controller
        application-crd-id: kubeflow-pipelines
    spec:
      {{- include "kubeflow-pipelines.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - "{{ with (coalesce .Values.global.imageRegistry .Values.workflowController.executorImage.registry) }}{{ . }}/{{ end }}{{ .Values.workflowController.executorImage.repository }}{{- if .Values.workflowController.executorImage.digest }}@{{ .Values.workflowController.executorImage.digest }}{{- else }}:{{ .Values.workflowController.executorImage.tag }}{{- end }}"
        command:
        - workflow-controller
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: "{{ with (coalesce .Values.global.imageRegistry .Values.workflowController.image.registry) }}{{ . }}/{{ end }}{{ .Values.workflowController.image.repository }}{{- if .Values.workflowController.image.digest }}@{{ .Values.workflowController.image.digest }}{{- else }}:{{ .Values.workflowController.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.workflowController.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6060
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 30
        name: workflow-controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 6060
        {{- with .Values.workflowController.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: workflow-controller
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo
