apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        - kubeflow
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
