global:
  # -- Global override for container image registry
  imageRegistry: ""
  # -- Global override for container image pull secrets
  imagePullSecrets: []

image:
  registry: ghcr.io
  repository: kubeflow/kubeflow/pvcviewer-controller
  tag: v1.10.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
