global:
  # -- Global override for container image registry
  imageRegistry: ""
  # -- Global override for container image pull secrets
  imagePullSecrets: []

image:
  registry: registry.suse.com
  repository: ai/containers/pvcviewer-controller
  tag: v1.10.0
  pullPolicy: IfNotPresent

replicaCount: 1

# Image injected into PVCViewer pods as the default viewer (filebrowser)
viewerImage: "registry.suse.com/ai/containers/filebrowser:v2.25.0"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
