apiVersion: v1
data:
  CLUSTER_DOMAIN: {{ .Values.configMapData.CLUSTER_DOMAIN | quote }}
  CULL_IDLE_TIME: '{{ .Values.cullingPolicy.cullIdleTime }}'
  ENABLE_CULLING: '{{ .Values.cullingPolicy.enableCulling }}'
  IDLENESS_CHECK_PERIOD: '{{ .Values.cullingPolicy.idlenessCheckPeriod }}'
  ISTIO_GATEWAY: {{ .Values.configMapData.ISTIO_GATEWAY | quote }}
  USE_ISTIO: {{ .Values.configMapData.USE_ISTIO | quote }}
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: notebook-controller-config-mf8876789d
  namespace: kubeflow
