{{- $root := . -}}
{{- range .Values.additionalUsers }}
{{- $emailSlug := .email | lower | replace "." "-" | replace "@" "--" }}
{{- $namespaceName := .namespace | default $emailSlug }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: {{ $namespaceName }}
stringData:
  accesskey: {{ $root.Values.pipelines.seaweedfs.accessKey | quote }}
  secretkey: {{ $root.Values.pipelines.seaweedfs.secretKey | quote }}
{{- end }}
