apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: kubeflow-user-example-com
stringData:
  accesskey: {{ .Values.pipelines.seaweedfs.accessKey | quote }}
  secretkey: {{ .Values.pipelines.seaweedfs.secretKey | quote }}
