apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-lgbserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8080'
  containers:
  - args:
    - --model_name={{`{{.Name}}`}}
    - --model_dir=/mnt/models
    - --http_port=8080
    - --nthread=1
    image: "{{ include "kserve.suseImageRegistry" (dict "ctx" . "registry" .Values.lgbServer.image.registry) }}/{{ .Values.lgbServer.image.repository }}{{- if .Values.lgbServer.image.digest }}@{{ .Values.lgbServer.image.digest }}{{- else }}:{{ .Values.lgbServer.image.tag }}{{- end }}"
    name: kserve-container
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
  protocolVersions:
  - v1
  supportedModelFormats:
  - autoSelect: true
    name: lightgbm
    version: '3'
