apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-pmmlserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8080'
  containers:
  - args:
    - --model_name={{`{{.Name}}`}}
    - --model_dir=/mnt/models
    - --http_port=8080
    image: "{{- $registry := include "kserve.suseImageRegistry" (dict "ctx" . "registry" .Values.pmmlServer.image.registry) -}}{{- if $registry }}{{ $registry }}/{{ end }}{{ .Values.pmmlServer.image.repository }}{{- if .Values.pmmlServer.image.digest }}@{{ .Values.pmmlServer.image.digest }}{{- else }}:{{ .Values.pmmlServer.image.tag }}{{- end }}"
    name: kserve-container
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
  protocolVersions:
  - v1
  supportedModelFormats:
  - autoSelect: true
    name: pmml
    version: '3'
  - autoSelect: true
    name: pmml
    version: '4'
