{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry-controller
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-registry-controller
  namespace: kubeflow
{{- end }}
