apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-pvc
  namespace: kubeflow
  labels:
    app: seaweedfs
    application-crd-id: kubeflow-pipelines
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.seaweedfs.persistence.storageClass }}
  storageClassName: {{ .Values.seaweedfs.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.seaweedfs.persistence.size }}
