{{- $root := . -}}
{{- if .Values.istio.ingressGateway.principal }}
{{- range .Values.additionalUsers }}
{{- $emailSlug := .email | lower | replace "." "-" | replace "@" "--" }}
{{- $namespaceName := .namespace | default $emailSlug }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: rancher-ingressgateway-access
  namespace: {{ $namespaceName }}
spec:
  rules:
  - from:
    - source:
        principals:
        - {{ $root.Values.istio.ingressGateway.principal | quote }}
    when:
    - key: request.headers[{{ $root.Values.userIdHeader }}]
      values:
      - {{ .email | quote }}
{{- end }}
{{- end }}
