{{- if .Values.jobset.controller.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    control-plane: jobset-controller-manager
  name: jobset-webhook-server-cert
  namespace: kubeflow
type: Opaque
data:
  tls.crt: ""
  tls.key: ""
{{- end }}
