apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry-ui
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-registry-ui
  namespace: kubeflow
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: model-registry
      app.kubernetes.io/component: model-registry-ui
      app.kubernetes.io/name: model-registry
      kustomize.component: model-registry
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: model-registry
        app.kubernetes.io/component: model-registry-ui
        app.kubernetes.io/name: model-registry
        kustomize.component: model-registry
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      {{- include "model-registry.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - --port=8080
        - --deployment-mode=kubeflow
        image: "{{ include "model-registry.suseImageRegistry" (dict "ctx" . "registry" .Values.ui.image.registry) }}/{{ .Values.ui.image.repository }}{{- if .Values.ui.image.digest }}@{{ .Values.ui.image.digest }}{{- else }}:{{ .Values.ui.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: false
        {{- with .Values.ui.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ui.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ui.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: model-registry-ui
        ports:
        - containerPort: 8080
          name: http
        {{- with .Values.ui.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: model-registry-ui
