apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    katib.kubeflow.org/component: mysql
  name: katib-mysql
  namespace: kubeflow
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      katib.kubeflow.org/component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        katib.kubeflow.org/component: mysql
    spec:
      securityContext:
        fsGroup: 1000
      {{- include "katib.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: katib-mysql-secrets
        - name: MYSQL_DATABASE
          value: katib
        image: "{{ with (coalesce .Values.global.imageRegistry .Values.mariadb.image.registry) }}{{ . }}/{{ end }}{{ .Values.mariadb.image.repository }}{{- if .Values.mariadb.image.digest }}@{{ .Values.mariadb.image.digest }}{{- else }}:{{ .Values.mariadb.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 5
        name: katib-mysql
        ports:
        - containerPort: {{ .Values.mariadb.port }}
          name: dbapi
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mariadb -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT
              1'
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 60
          periodSeconds: 15
        {{- with .Values.mariadb.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: katib-mysql
      volumes:
      - name: katib-mysql
        persistentVolumeClaim:
          claimName: katib-mysql
