apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    katib.kubeflow.org/component: ui
  name: katib-ui
  namespace: kubeflow
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      katib.kubeflow.org/component: ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        katib.kubeflow.org/component: ui
    spec:
      {{- include "katib.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - --port={{ .Values.ui.port }}
        command:
        - ./katib-ui
        env:
        - name: KATIB_CORE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_DISABLE_AUTH
          value: {{ .Values.ui.env.APP_DISABLE_AUTH | quote }}
        image: "{{ include "katib.suseImageRegistry" (dict "ctx" . "registry" .Values.ui.image.registry) }}/{{ .Values.ui.image.repository }}{{- if .Values.ui.image.digest }}@{{ .Values.ui.image.digest }}{{- else }}:{{ .Values.ui.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        name: katib-ui
        ports:
        - containerPort: {{ .Values.ui.port }}
          name: ui
        {{- with .Values.ui.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ui.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ui.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: katib-ui
