apiVersion: v1
data:
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: e7973912
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.8.0
  name: config-defaults
  namespace: knative-serving