apiVersion: v1
data:
  progressDeadline: 600s
  queue-sidecar-image: "{{ with (coalesce .Values.global.imageRegistry .Values.queueSidecarImage.image.registry) }}{{ . }}/{{ end }}{{ .Values.queueSidecarImage.image.repository }}{{- if .Values.queueSidecarImage.image.digest }}@{{ .Values.queueSidecarImage.image.digest }}{{- else }}:{{ .Values.queueSidecarImage.image.tag }}{{- end }}"
  registries-skipping-tag-resolving: "{{ .Values.registriesSkippingTagResolving }}"
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: dd7ee769
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.8.0
  name: config-deployment
  namespace: knative-serving
