apiVersion: v1
data:
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: b0f3c6f2
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.8.0
  name: config-logging
  namespace: knative-serving