{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metadata-grpc-deployment
  namespace: kubeflow
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      component: metadata-grpc
      application-crd-id: kubeflow-pipelines
{{- end }}
