{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workflow-controller
  namespace: kubeflow
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app: workflow-controller
      application-crd-id: kubeflow-pipelines
{{- end }}
