apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: model-registry
  namespace: kubeflow
spec:
  gateways:
  - {{ .Values.global.gateway.name | default "kubeflow/kubeflow-gateway" }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualServicePrefix }}
    route:
    - destination:
        host: model-registry-service.kubeflow.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
