apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflow-trainer-config
  namespace: kubeflow
data:
  controller_manager_config.yaml: |
    apiVersion: config.trainer.kubeflow.org/v1alpha1
    kind: Configuration
    health:
      healthProbeBindAddress: :8081
      readinessEndpointName: readyz
      livenessEndpointName: healthz
    metrics:
      bindAddress: :8080
      secureServing: false
    webhook:
      port: 9443
      host: ""
    leaderElection:
      leaderElect: true
      resourceName: trainer.kubeflow.org
      resourceNamespace: ""
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
    controller:
      groupKindConcurrency:
        TrainJob.trainer.kubeflow.org: 5
        TrainingRuntime.trainer.kubeflow.org: 1
        ClusterTrainingRuntime.trainer.kubeflow.org: 1
    certManagement:
      enable: true
      webhookServiceName: kubeflow-trainer-controller-manager
      webhookSecretName: kubeflow-trainer-webhook-cert
    clientConnection:
      qps: 50
      burst: 100
