{{- if .Values.kserve.storageContainer.enabled }}
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry-storage-initializer
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-registry-storage-initializer
spec:
  container:
    name: storage-initializer
    image: "{{- $registry := include "model-registry.suseImageRegistry" (dict "ctx" . "registry" .Values.kserve.storageContainer.image.registry) -}}{{- if $registry }}{{ $registry }}/{{ end }}{{ .Values.kserve.storageContainer.image.repository }}{{- if .Values.kserve.storageContainer.image.digest }}@{{ .Values.kserve.storageContainer.image.digest }}{{- else }}:{{ .Values.kserve.storageContainer.image.tag }}{{- end }}"
    imagePullPolicy: {{ .Values.kserve.storageContainer.image.pullPolicy }}
    env:
    - name: MODEL_REGISTRY_BASE_URL
      value: "model-registry-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 1Gi
  supportedUriFormats:
  - prefix: "model-registry://"
{{- end }}
