apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tensorboard-controller
    control-plane: controller-manager
    kustomize.component: tensorboard-controller
  name: tensorboard-controller-deployment
  namespace: kubeflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tensorboard-controller
      control-plane: controller-manager
      kustomize.component: tensorboard-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: tensorboard-controller
        control-plane: controller-manager
        kustomize.component: tensorboard-controller
    spec:
      {{- include "tensorboard-controller.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        command:
        - /manager
        envFrom:
        - configMapRef:
            name: tensorboard-controller-config-b98cb9gk9k
        image: "{{ include "tensorboard-controller.suseImageRegistry" (dict "ctx" . "registry" .Values.manager.image.registry) }}/{{ .Values.manager.image.repository }}{{- if .Values.manager.image.digest }}@{{ .Values.manager.image.digest }}{{- else }}:{{ .Values.manager.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        {{- with .Values.manager.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: manager
        {{- with .Values.manager.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.manager.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: "{{ include "tensorboard-controller.suseApplicationCollectionRegistry" (dict "ctx" . "registry" .Values.kubeRbacProxy.image.registry) }}/{{ .Values.kubeRbacProxy.image.repository }}{{- if .Values.kubeRbacProxy.image.digest }}@{{ .Values.kubeRbacProxy.image.digest }}{{- else }}:{{ .Values.kubeRbacProxy.image.tag }}{{- end }}"
        imagePullPolicy: {{ .Values.kubeRbacProxy.image.pullPolicy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          {{- toYaml .Values.kubeRbacProxy.resources | nindent 10 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      serviceAccountName: tensorboard-controller-controller-manager
      terminationGracePeriodSeconds: 10
