{{- $kir := index .Values "kubeflow-istio-resources" }}
{{- $tls := $kir.tls | default dict }}
{{- $tlsSource := $tls.source | default "" }}
{{- if eq $tlsSource "selfSigned" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubeflow-selfsigned
  namespace: istio-system
spec:
  selfSigned: {}
{{- end }}
