apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvcviewer-leader-election
  namespace: kubeflow
  labels:
    app: pvcviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pvcviewer-leader-election
subjects:
- kind: ServiceAccount
  name: pvcviewer-controller-manager
  namespace: kubeflow
