{{- if .Values.catalog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: model-registry
    app.kubernetes.io/component: model-catalog-server
    app.kubernetes.io/name: model-registry
    kustomize.component: model-registry
  name: model-catalog-sources
  namespace: kubeflow
data:
  sources.yaml: |
    {{- .Values.catalog.sources | nindent 4 }}
{{- end }}
